### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mindcodings** [wochenlong/rr-tag#1]
您好，请问发送maketag和rr-tag 一直显示等待中。
![image](https://user-images.githubusercontent.com/32920883/229454414-5370de72-849b-448a-8985-6e6e8278669d.png)
这是怎么回事呀   gpt服务也正常的  dvc也正常

**Comment by wochenlong** [comment]
gpt服务或dvc服务有正常开启吗，看看日志

**Comment by wochenlong** [comment]
1.1.5版本已经发布，你可以查看此bug有没有被修复
